app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Atlas VPN
publisher_url: https://buy.vannp.com
display_name: Atlas VPN
create_desktop_icon: true
install_dir_name: '{autopf64}\Atlas VPN'
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
